/**
 * v0.7.2: ACCEPTANCE.md 模板生成 — 人类可读的验收报告导出。
 *
 * 将 AcceptanceResult 渲染为 Markdown，落盘到 .patchwarden/tasks/{task_id}/ACCEPTANCE.md。
 */

import type { AcceptanceResult, AcceptanceEvidence } from "./acceptanceEngine.js";
import { PATCHWARDEN_VERSION } from "../version.js";

/**
 * 生成 ACCEPTANCE.md 内容。
 */
export function renderAcceptanceMarkdown(
  taskId: string,
  result: AcceptanceResult,
  evidence: AcceptanceEvidence
): string {
  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push("# Acceptance Report — " + taskId);
  lines.push("");
  lines.push("Generated: " + now);
  lines.push("");

  // ── Verdict ──────────────────────────────────────────────
  lines.push("## Verdict");
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("| --- | --- |");
  lines.push("| Verdict | **" + result.verdict + "** |");
  lines.push("| Acceptance Status | " + (result.acceptance_status ?? "null") + " |");
  lines.push("| Reason | " + result.reason + " |");
  lines.push("| Next Suggested Task | " + result.next_suggested_task + " |");
  lines.push("");

  // ── Evidence Summary ────────────────────────────────────
  lines.push("## Evidence Summary");
  lines.push("");
  lines.push("| Evidence | Present |");
  lines.push("| --- | --- |");
  lines.push("| result.md | " + (evidence.result_md_exists ? "YES" : "NO") + " |");
  lines.push("| result.json | " + (evidence.result_json_exists ? "YES" : "NO") + " |");
  lines.push("| verify.json | " + (evidence.verify_json_exists ? "YES" : "NO") + " |");
  lines.push("| test.log | " + (evidence.test_log_exists ? "YES" : "NO") + " |");
  lines.push("| git.diff | " + (evidence.git_diff_exists ? "YES" : "NO") + " |");
  lines.push("| verify_status | " + (evidence.verify_status ?? "N/A") + " |");
  lines.push("| artifact_status | " + (evidence.artifact_status ?? "N/A") + " |");
  lines.push("| out_of_scope_changes | " + evidence.new_out_of_scope_changes.length + " |");
  lines.push("| release_claims_unverified | " + (evidence.release_claims_unverified ? "YES" : "NO") + " |");
  lines.push("");

  // ── Task Metadata ────────────────────────────────────────
  if (evidence.goal || evidence.scope || evidence.forbidden || evidence.verification || evidence.done_evidence) {
    lines.push("## Task Acceptance Criteria");
    lines.push("");
    if (evidence.goal) {
      lines.push("- **Goal**: " + evidence.goal);
    }
    if (evidence.scope && evidence.scope.length > 0) {
      lines.push("- **Scope**: " + evidence.scope.join(", "));
    }
    if (evidence.forbidden && evidence.forbidden.length > 0) {
      lines.push("- **Forbidden**: " + evidence.forbidden.join(", "));
    }
    if (evidence.verification && evidence.verification.length > 0) {
      lines.push("- **Verification**: " + evidence.verification.join(", "));
    }
    if (evidence.done_evidence && evidence.done_evidence.length > 0) {
      lines.push("- **Done Evidence**: " + evidence.done_evidence.join(", "));
    }
    lines.push("");
  }

  // ── Fail Checks ─────────────────────────────────────────
  if (result.fail_checks.length > 0) {
    lines.push("## Fail-Level Checks");
    lines.push("");
    for (const check of result.fail_checks) {
      lines.push("- **" + check.name + "**: " + check.detail);
    }
    lines.push("");
  }

  // ── Warn Checks ─────────────────────────────────────────
  if (result.warn_checks.length > 0) {
    lines.push("## Warn-Level Checks");
    lines.push("");
    for (const check of result.warn_checks) {
      lines.push("- **" + check.name + "**: " + check.detail);
    }
    lines.push("");
  }

  // ── Reasons ─────────────────────────────────────────────
  if (result.reasons.length > 0) {
    lines.push("## Reasons");
    lines.push("");
    for (const reason of result.reasons) {
      lines.push("- " + reason);
    }
    lines.push("");
  }

  // ── Required Evidence ────────────────────────────────────
  if (result.required_evidence.length > 0) {
    lines.push("## Required Evidence");
    lines.push("");
    for (const reqEvidence of result.required_evidence) {
      lines.push("- " + reqEvidence);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("This report was generated by PatchWarden v" + PATCHWARDEN_VERSION + " acceptanceEngine.");
  lines.push("");

  return lines.join("\n");
}
