/**
 * Shared tool registry for Safe-Bifrost MCP server.
 * Used by both stdio (index.ts) and HTTP (httpServer.ts) transports.
 */

import type { Server } from "@modelcontextprotocol/sdk/server/index.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { getConfig } from "../config.js";
import { savePlan } from "../tools/savePlan.js";
import { getPlan } from "../tools/getPlan.js";
import { createTask } from "../tools/createTask.js";
import { getTaskStatus } from "../tools/getTaskStatus.js";
import { getResult, getDiff, getTestLog } from "../tools/taskOutputs.js";
import { listWorkspace } from "../tools/listWorkspace.js";
import { readWorkspaceFile } from "../tools/readWorkspaceFile.js";
import { runTask } from "../runner/runTask.js";

// ── Tool definitions ──────────────────────────────────────────────

export interface ToolDef {
  name: string;
  description: string;
  inputSchema: {
    type: "object";
    properties: Record<string, unknown>;
    required?: string[];
  };
}

export function getToolDefs(): ToolDef[] {
  const config = getConfig();
  const tools: ToolDef[] = [
    {
      name: "save_plan",
      description:
        "Save an execution plan — ChatGPT writes the plan, Safe-Bifrost stores it for local agent execution.",
      inputSchema: {
        type: "object",
        properties: {
          title: { type: "string", description: "Plan title" },
          content: { type: "string", description: "Plan content in Markdown" },
        },
        required: ["title", "content"],
      },
    },
    {
      name: "get_plan",
      description: "Read a saved plan by its plan_id.",
      inputSchema: {
        type: "object",
        properties: {
          plan_id: { type: "string", description: "Plan ID returned by save_plan" },
        },
        required: ["plan_id"],
      },
    },
    {
      name: "create_task",
      description:
        "Create a task from a plan. Links a plan to a local agent for execution. The local watcher will pick up pending tasks automatically.",
      inputSchema: {
        type: "object",
        properties: {
          plan_id: { type: "string", description: "Plan ID from save_plan" },
          agent: {
            type: "string",
            description: 'Agent name: "codex" or "opencode"',
          },
          repo_path: {
            type: "string",
            description: "Optional repo path (defaults to workspace root)",
          },
          test_command: {
            type: "string",
            description: "Optional test command from the allowlist",
          },
        },
        required: ["plan_id", "agent"],
      },
    },
    {
      name: "get_task_status",
      description: "Check the status of a task: pending, running, done, or failed.",
      inputSchema: {
        type: "object",
        properties: {
          task_id: { type: "string", description: "Task ID from create_task" },
        },
        required: ["task_id"],
      },
    },
    {
      name: "get_result",
      description: "Read the execution result (result.md) for a completed task.",
      inputSchema: {
        type: "object",
        properties: {
          task_id: { type: "string", description: "Task ID" },
        },
        required: ["task_id"],
      },
    },
    {
      name: "get_diff",
      description: "Read the git diff generated by a task execution.",
      inputSchema: {
        type: "object",
        properties: {
          task_id: { type: "string", description: "Task ID" },
        },
        required: ["task_id"],
      },
    },
    {
      name: "get_test_log",
      description: "Read the test log from a task execution.",
      inputSchema: {
        type: "object",
        properties: {
          task_id: { type: "string", description: "Task ID" },
        },
        required: ["task_id"],
      },
    },
    {
      name: "list_workspace",
      description:
        "List files and directories within the workspace (sensitive files excluded).",
      inputSchema: {
        type: "object",
        properties: {
          path: {
            type: "string",
            description: "Optional relative path within workspace (default: root)",
          },
        },
      },
    },
    {
      name: "read_workspace_file",
      description:
        "Read a file within the workspace. Sensitive files (secrets, keys, tokens) are blocked.",
      inputSchema: {
        type: "object",
        properties: {
          path: {
            type: "string",
            description: "Relative path to a file inside the workspace",
          },
        },
        required: ["path"],
      },
    },
  ];

  // run_task: only available when explicitly enabled
  if ((config as any).enableRunTaskTool === true) {
    tools.push({
      name: "run_task",
      description:
        "Manually trigger execution of a pending task. WARNING: requires enableRunTaskTool=true in config. Prefer using the local watcher instead.",
      inputSchema: {
        type: "object",
        properties: {
          task_id: { type: "string", description: "Task ID to execute" },
        },
        required: ["task_id"],
      },
    });
  }

  return tools;
}

// ── Request handler ───────────────────────────────────────────────

export function handleToolCall(name: string, args: Record<string, unknown> | undefined) {
  switch (name) {
    case "save_plan": {
      return toResult(
        savePlan({
          title: String(args?.title ?? ""),
          content: String(args?.content ?? ""),
        })
      );
    }

    case "get_plan": {
      return toResult(
        getPlan({ plan_id: String(args?.plan_id ?? "") })
      );
    }

    case "create_task": {
      return toResult(
        createTask({
          plan_id: String(args?.plan_id ?? ""),
          agent: String(args?.agent ?? ""),
          repo_path: args?.repo_path ? String(args.repo_path) : undefined,
          test_command: args?.test_command ? String(args.test_command) : undefined,
        })
      );
    }

    case "get_task_status": {
      return toResult(getTaskStatus(String(args?.task_id ?? "")));
    }

    case "get_result": {
      return toResult(getResult(String(args?.task_id ?? "")));
    }

    case "get_diff": {
      return toResult(getDiff(String(args?.task_id ?? "")));
    }

    case "get_test_log": {
      return toResult(getTestLog(String(args?.task_id ?? "")));
    }

    case "list_workspace": {
      return toResult(
        listWorkspace(args?.path ? String(args.path) : undefined)
      );
    }

    case "read_workspace_file": {
      return toResult(readWorkspaceFile(String(args?.path ?? "")));
    }

    case "run_task": {
      const config = getConfig();
      if ((config as any).enableRunTaskTool !== true) {
        throw new Error(
          "run_task is disabled. Set enableRunTaskTool: true in config to enable. Prefer using the local watcher (npm run watch)."
        );
      }
      const taskId = String(args?.task_id ?? "");
      const result = runTask(taskId);
      return toResult(result);
    }

    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

function toResult(data: unknown) {
  return {
    content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }],
  };
}

// ── Register on MCP Server ────────────────────────────────────────

export function registerTools(server: Server) {
  server.setRequestHandler(ListToolsRequestSchema, async () => {
    return { tools: getToolDefs() };
  });

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args } = request.params;
    try {
      return handleToolCall(name, args);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        content: [{ type: "text" as const, text: JSON.stringify({ error: message }) }],
        isError: true,
      };
    }
  });
}
